'use strict';
const fs=require('node:fs'),path=require('node:path');
const A=require('./_assert.js');
const root=path.resolve(__dirname,'..');
const html=fs.readFileSync(path.join(root,'frontend','index.html'),'utf8');
const js=fs.readFileSync(path.join(root,'frontend','app','autonomy-city.js'),'utf8');
const css=fs.readFileSync(path.join(root,'frontend','css','autonomy-city.css'),'utf8');
const query=fs.readFileSync(path.join(root,'frontend','app','queryspine.js'),'utf8');
const mediaHome=fs.readFileSync(path.join(root,'frontend','app','media-home.js'),'utf8');
const mediaSports=fs.readFileSync(path.join(root,'frontend','app','media-sports.js'),'utf8');
const renderer=fs.readFileSync(path.join(root,'frontend','app','autonomy-renderer.js'),'utf8');

A.ok(html.includes('css/autonomy-city.css'),'Autonomy City stylesheet is loaded');
A.ok(html.includes('app/autonomy-city.js'),'Autonomy City module is loaded');
A.ok(html.includes('app/autonomy-renderer.js'),'isometric renderer is loaded');
A.ok(js.includes('AutonomyRenderer.mount(root)'),'city shell mounts the isometric renderer');
A.ok(js.includes("AutonomyRenderer.focus(id)"),'campus selection moves the presentation camera');
A.ok(js.includes('AutonomyRenderer.sync(lastCommand)'),'live enterprise state drives city activity cues');
A.ok(query.includes("define('command-hq'"),'Command HQ has a shared QuerySpine resource');
A.ok(query.includes("path: '/api/enterprise/command'"),'Command HQ reads from dedicated enterprise endpoint');
A.ok(js.includes('AUTONOMY CITY'),'first-pass launcher is present');
A.ok(js.includes('COMMAND HQ'),'Command HQ campus is present');
A.ok(js.includes('MEDIA CAMPUS'),'Media campus is present');
A.ok(js.includes('R&D / INNOVATION'),'R&D campus is present');
A.ok(js.includes('UNDER CONSTRUCTION'),'future campuses are explicitly construction-state');
A.ok(js.includes('ENTERPRISE DATA LINK NOT ACTIVE YET'),'missing enterprise data is labeled unavailable');
A.ok(!js.includes('Math.random('),'preview does not fabricate changing metrics');
A.ok(css.includes('.ac-hq'),'Command HQ has dedicated visual treatment');
A.ok(js.includes('ac-building-hq'),'Command HQ uses its own civic building geometry');
A.ok(css.includes('.ac-building-hq .ac-dome'),'Command HQ carries a distinct capitol dome');
A.ok(css.includes('.ac-rendered-iso'),'city has isometric render mode');
A.ok(css.includes('.ac-camera-controls'),'isometric camera controls are styled');
A.ok(css.includes('.ac-campus.is-selected'),'selected campus has a focused visual state');
A.ok(css.includes('.ac-campus.has-live'),'activity lighting requires a live state class');
A.ok(css.includes('@keyframes ac-water-drift'),'ambient environment motion is present');
A.ok(css.includes('.media-flow-live'),'HQ to Media flow only animates from a live-state class');
A.ok(css.includes('.ac-enterprise-flow'),'district connection layer is rendered');
A.ok(css.includes('.ac-rendered-iso.has-focus'),'selected district visually separates from the wider city');
A.ok(renderer.includes('ac-district-stage'),'renderer creates district entry staging');
A.ok(renderer.includes('ac-arrival-zones'),'renderer creates district arrival zones');
A.ok(renderer.includes('ac-grand-boulevard'),'renderer creates Command approach boulevard');
A.ok(renderer.includes('ac-campus-gates'),'renderer creates labeled campus gateways');
A.ok(renderer.includes('ac-parallax'),'renderer creates foreground/background parallax scenery');
A.ok(html.includes('css/autonomy-city-motion.css'),'ambient motion stylesheet is loaded');
A.ok(css.includes('.ac-water'),'campus layout reserves landscaped/water breathing room');
A.ok(css.includes('.ac-road:after'),'roads include hierarchy markings');
A.ok(css.includes('.ac-hq-metrics'),'Command HQ includes an executive metric strip');
A.ok(js.includes('ENTER MEDIA CAMPUS'),'Command HQ can drill into Media');
A.ok(mediaSports.includes('Sports Operations'),'Media campus exposes operating areas');
A.ok(mediaHome.includes('RIGHTS & MONETIZATION'),'Media campus exposes the monetization gate area');
A.ok(mediaHome.includes('BACK TO COMMAND HQ'),'campus drilldowns preserve executive back-navigation');
A.ok(html.includes('app/media-home.js'),'Media home module is loaded');
A.ok(html.includes('app/media-sports.js'),'Sports operations module is loaded');
A.ok(html.includes('app/media-management.js'),'Media management module is loaded');
A.ok(html.includes('app/media-rights.js'),'Media rights module is loaded');
A.ok(html.includes('app/media-performance.js'),'Media performance module is loaded');
A.ok(html.includes('app/media-workforce.js'),'Media workforce module is loaded');
A.ok(html.includes('app/media-future.js'),'future Media division module is loaded');
A.ok(js.includes('openMedia'),'Autonomy City routes into Media sector surfaces');
A.ok(css.includes('.ac-campus-room-grid'),'campus interiors have a dedicated drilldown layout');
A.report('autonomy-city-surface.test');
