'use strict';
const fs=require('node:fs'),path=require('node:path');
const A=require('./_assert.js');
const root=path.resolve(__dirname,'..');
const html=fs.readFileSync(path.join(root,'frontend','index.html'),'utf8');
const js=fs.readFileSync(path.join(root,'frontend','app','autonomy-city.js'),'utf8');
const css=fs.readFileSync(path.join(root,'frontend','css','autonomy-city.css'),'utf8');
const query=fs.readFileSync(path.join(root,'frontend','app','queryspine.js'),'utf8');

A.ok(html.includes('css/autonomy-city.css'),'Autonomy City stylesheet is loaded');
A.ok(html.includes('app/autonomy-city.js'),'Autonomy City module is loaded');
A.ok(query.includes("define('command-hq'"),'Command HQ has a shared QuerySpine resource');
A.ok(query.includes("path: '/api/enterprise/command'"),'Command HQ reads from dedicated enterprise endpoint');
A.ok(js.includes('AUTONOMY CITY'),'first-pass launcher is present');
A.ok(js.includes('COMMAND HQ'),'Command HQ campus is present');
A.ok(js.includes('MEDIA CAMPUS'),'Media campus is present');
A.ok(js.includes('R&D / INNOVATION'),'R&D campus is present');
A.ok(js.includes('UNDER CONSTRUCTION'),'future campuses are explicitly construction-state');
A.ok(js.includes('ENTERPRISE DATA LINK NOT ACTIVE YET'),'missing enterprise data is labeled unavailable');
A.ok(!js.includes('Math.random('),'preview does not fabricate changing metrics');
A.ok(css.includes('.ac-hq'),'Command HQ has dedicated visual treatment');
A.ok(js.includes('ac-building-hq'),'Command HQ uses its own civic building geometry');
A.ok(css.includes('.ac-building-hq .ac-dome'),'Command HQ carries a distinct capitol dome');
A.ok(css.includes('.ac-water'),'campus layout reserves landscaped/water breathing room');
A.ok(css.includes('.ac-hq-metrics'),'Command HQ includes an executive metric strip');
A.ok(js.includes('ENTER MEDIA CAMPUS'),'Command HQ can drill into Media');
A.ok(js.includes('SPORTS OPERATIONS'),'Media campus exposes operating areas');
A.ok(js.includes('RIGHTS & MONETIZATION'),'Media campus exposes the monetization gate area');
A.ok(js.includes('BACK TO COMMAND HQ'),'campus drilldowns preserve executive back-navigation');
A.ok(html.includes('app/media-home.js'),'Media home module is loaded');
A.ok(html.includes('app/media-sports.js'),'Sports operations module is loaded');
A.ok(html.includes('app/media-management.js'),'Media management module is loaded');
A.ok(html.includes('app/media-rights.js'),'Media rights module is loaded');
A.ok(html.includes('app/media-performance.js'),'Media performance module is loaded');
A.ok(html.includes('app/media-workforce.js'),'Media workforce module is loaded');
A.ok(html.includes('app/media-future.js'),'future Media division module is loaded');
A.ok(js.includes('openMedia'),'Autonomy City routes into Media sector surfaces');
A.ok(css.includes('.ac-campus-room-grid'),'campus interiors have a dedicated drilldown layout');
A.report('autonomy-city-surface.test');
